FROM nginx:latest

# create streams folder
RUN mkdir /etc/nginx/streams-enabled

# copy config to streams
COPY nginx.conf /etc/nginx/nginx.conf

RUN echo "include /etc/nginx/streams-enabled/*.conf;" >> /etc/nginx/nginx.conf

EXPOSE 53/udp