version: '3.8'

services:
  ddns:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5300:5300/udp"
    restart: always
    environment:
      - FLASK_ENV=production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "53:53/udp"
    restart: always
    depends_on:
      - ddns
