version: '3.8'

services:
  ddns:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5300:5300/udp"
    restart: always
    environment:
      - FLASK_ENV=production
